version = 1

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
plugins = ["vue"]

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "rubocop"
enabled = true
